"""remove_sidebar_collapsed

Revision ID: 7ab3cdc1b72e
Revises: b66e65d9221b
Create Date: 2026-04-02 14:56:27.357695
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7ab3cdc1b72e'
down_revision: Union[str, None] = 'b66e65d9221b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sidebar_collapsed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sidebar_collapsed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
